"""add avatar to Pet

Revision ID: 23a4ebe43ed5
Revises: dabd6b1bb1ff
Create Date: 2023-05-20 14:42:20.422519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a4ebe43ed5'
down_revision = 'dabd6b1bb1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
